name: Aliyun CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup bun
        uses: oven-sh/setup-bun@v2

      - name: Install & Build
        run: bun install && bun run build

      - name: Upload to OSS
        uses: chf007/aliyun-oss-upload-action@main
        env:
          OSS_ACCESS_KEY_ID: ${{ secrets.ALI_KEY_ID }}
          OSS_ACCESS_KEY_SECRET: ${{ secrets.ALI_KEY_SECRET }}
        with:
          source-dir: './doc_build'
          dest-dir: '/'
          bucket: ${{ secrets.ALI_BUCKET }}
          region: 'oss-cn-hangzhou'
